name: Prose lint

on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  vale:
    name: Vale prose check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vale linter
        uses: errata-ai/vale-action@v2.1.1
        with:
          reporter: github-pr-review
          fail_on_error: false
